const heroes = [
  { name: "antimage", id: 1, localized_name: "Anti-Mage", short: "AM" },
  { name: "axe", id: 2, localized_name: "Axe", short: "Axe" },
  { name: "bane", id: 3, localized_name: "Bane", short: "Bane" },
  { name: "bloodseeker", id: 4, localized_name: "Bloodseeker", short: "Blood" },
  {
    name: "crystal_maiden",
    id: 5,
    localized_name: "Crystal Maiden",
    short: "CM",
  },
  { name: "drow_ranger", id: 6, localized_name: "Drow Ranger", short: "Drow" },
  {
    name: "earthshaker",
    id: 7,
    localized_name: "Earthshaker",
    short: "Shaker",
  },
  { name: "juggernaut", id: 8, localized_name: "Juggernaut", short: "Jugg" },
  { name: "mirana", id: 9, localized_name: "Mirana", short: "Mirana" },
  { name: "morphling", id: 10, localized_name: "Morphling", short: "Morph" },
  { name: "nevermore", id: 11, localized_name: "Shadow Fiend", short: "SF" },
  {
    name: "phantom_lancer",
    id: 12,
    localized_name: "Phantom Lancer",
    short: "PL",
  },
  { name: "puck", id: 13, localized_name: "Puck", short: "Puck" },
  { name: "pudge", id: 14, localized_name: "Pudge", short: "Puck" },
  { name: "razor", id: 15, localized_name: "Razor", short: "Razor" },
  { name: "sand_king", id: 16, localized_name: "Sand King", short: "SK" },
  {
    name: "storm_spirit",
    id: 17,
    localized_name: "Storm Spirit",
    short: "Storm",
  },
  { name: "sven", id: 18, localized_name: "Sven", short: "Sven" },
  { name: "tiny", id: 19, localized_name: "Tiny", short: "Tiny" },
  {
    name: "vengefulspirit",
    id: 20,
    localized_name: "Vengeful Spirit",
    short: "Venge",
  },
  { name: "windrunner", id: 21, localized_name: "Windranger", short: "Wind" },
  { name: "zuus", id: 22, localized_name: "Zeus", short: "Zeus" },
  { name: "kunkka", id: 23, localized_name: "Kunkka", short: "Kunkka" },
  { name: "lina", id: 25, localized_name: "Lina", short: "Lina" },
  { name: "lich", id: 31, localized_name: "Lich", short: "Lich" },
  { name: "lion", id: 26, localized_name: "Lion", short: "Lion" },
  {
    name: "shadow_shaman",
    id: 27,
    localized_name: "Shadow Shaman",
    short: "Shaman",
  },
  { name: "slardar", id: 28, localized_name: "Slardar", short: "Slardar" },
  { name: "tidehunter", id: 29, localized_name: "Tidehunter", short: "Tide" },
  { name: "witch_doctor", id: 30, localized_name: "Witch Doctor", short: "WD" },
  { name: "riki", id: 32, localized_name: "Riki", short: "Riki" },
  { name: "enigma", id: 33, localized_name: "Enigma", short: "Enigma" },
  { name: "tinker", id: 34, localized_name: "Tinker", short: "Tinker" },
  { name: "sniper", id: 35, localized_name: "Sniper", short: "Sniper" },
  { name: "necrolyte", id: 36, localized_name: "Necrophos", short: "Necro" },
  { name: "warlock", id: 37, localized_name: "Warlock", short: "Wlock" },
  {
    name: "beastmaster",
    id: 38,
    localized_name: "Beastmaster",
    short: "Beast",
  },
  {
    name: "queenofpain",
    id: 39,
    localized_name: "Queen of Pain",
    short: "QoP",
  },
  { name: "venomancer", id: 40, localized_name: "Venomancer", short: "Veno" },
  {
    name: "faceless_void",
    id: 41,
    localized_name: "Faceless Void",
    short: "Void",
  },
  { name: "skeleton_king", id: 42, localized_name: "Wraith King", short: "WK" },
  {
    name: "death_prophet",
    id: 43,
    localized_name: "Death Prophet",
    short: "DP",
  },
  {
    name: "phantom_assassin",
    id: 44,
    localized_name: "Phantom Assassin",
    short: "PA",
  },
  { name: "pugna", id: 45, localized_name: "Pugna", short: "Pugna" },
  {
    name: "templar_assassin",
    id: 46,
    localized_name: "Templar Assassin",
    short: "TA",
  },
  { name: "viper", id: 47, localized_name: "Viper", short: "Viper" },
  { name: "luna", id: 48, localized_name: "Luna", short: "Luna" },
  {
    name: "dragon_knight",
    id: 49,
    localized_name: "Dragon Knight",
    short: "DK",
  },
  { name: "dazzle", id: 50, localized_name: "Dazzle", short: "Dazz" },
  { name: "rattletrap", id: 51, localized_name: "Clockwerk", short: "Clock" },
  { name: "leshrac", id: 52, localized_name: "Leshrac", short: "Lesh" },
  { name: "furion", id: 53, localized_name: "Nature's Prophet", short: "NP" },
  {
    name: "life_stealer",
    id: 54,
    localized_name: "Lifestealer",
    short: "Naix",
  },
  { name: "dark_seer", id: 55, localized_name: "Dark Seer", short: "DS" },
  { name: "clinkz", id: 56, localized_name: "Clinkz", short: "Clinkz" },
  { name: "omniknight", id: 57, localized_name: "Omniknight", short: "Omni" },
  { name: "enchantress", id: 58, localized_name: "Enchantress", short: "Ench" },
  { name: "huskar", id: 59, localized_name: "Huskar", short: "Huskar" },
  {
    name: "night_stalker",
    id: 60,
    localized_name: "Night Stalker",
    short: "NS",
  },
  {
    name: "broodmother",
    id: 61,
    localized_name: "Broodmother",
    short: "Brood",
  },
  {
    name: "bounty_hunter",
    id: 62,
    localized_name: "Bounty Hunter",
    short: "BH",
  },
  { name: "weaver", id: 63, localized_name: "Weaver", short: "Weaver" },
  { name: "jakiro", id: 64, localized_name: "Jakiro", short: "Jakiro" },
  { name: "batrider", id: 65, localized_name: "Batrider", short: "Bat" },
  { name: "chen", id: 66, localized_name: "Chen", short: "Chen" },
  { name: "spectre", id: 67, localized_name: "Spectre", short: "Spect" },
  { name: "doom_bringer", id: 69, localized_name: "Doom", short: "Doom" },
  {
    name: "ancient_apparition",
    id: 68,
    localized_name: "Ancient Apparition",
    short: "AA",
  },
  { name: "ursa", id: 70, localized_name: "Ursa", short: "Ursa" },
  {
    name: "spirit_breaker",
    id: 71,
    localized_name: "Spirit Breaker",
    short: "SB",
  },
  { name: "gyrocopter", id: 72, localized_name: "Gyrocopter", short: "Gyro" },
  { name: "alchemist", id: 73, localized_name: "Alchemist", short: "Alch" },
  { name: "invoker", id: 74, localized_name: "Invoker", short: "Invo" },
  { name: "silencer", id: 75, localized_name: "Silencer", short: "Silencer" },
  {
    name: "obsidian_destroyer",
    id: 76,
    localized_name: "Outworld Destroyer",
    short: "OD",
  },
  { name: "lycan", id: 77, localized_name: "Lycan", short: "Lycan" },
  { name: "brewmaster", id: 78, localized_name: "Brewmaster", short: "Brew" },
  { name: "shadow_demon", id: 79, localized_name: "Shadow Demon", short: "SD" },
  { name: "lone_druid", id: 80, localized_name: "Lone Druid", short: "LD" },
  { name: "chaos_knight", id: 81, localized_name: "Chaos Knight", short: "CK" },
  { name: "meepo", id: 82, localized_name: "Meepo", short: "Meepo" },
  {
    name: "treant",
    id: 83,
    localized_name: "Treant Protector",
    short: "Treant",
  },
  { name: "ogre_magi", id: 84, localized_name: "Ogre Magi", short: "Ogre" },
  { name: "undying", id: 85, localized_name: "Undying", short: "Undy" },
  { name: "rubick", id: 86, localized_name: "Rubick", short: "Rubick" },
  { name: "disruptor", id: 87, localized_name: "Disruptor", short: "Disrupt" },
  {
    name: "nyx_assassin",
    id: 88,
    localized_name: "Nyx Assassin",
    short: "Nyx",
  },
  { name: "naga_siren", id: 89, localized_name: "Naga Siren", short: "Naga" },
  {
    name: "keeper_of_the_light",
    id: 90,
    localized_name: "Keeper of the Light",
    short: "KotL",
  },
  { name: "wisp", id: 91, localized_name: "Io", short: "Io" },
  { name: "visage", id: 92, localized_name: "Visage", short: "Visage" },
  { name: "slark", id: 93, localized_name: "Slark", short: "Slark" },
  { name: "medusa", id: 94, localized_name: "Medusa", short: "Dusa" },
  {
    name: "troll_warlord",
    id: 95,
    localized_name: "Troll Warlord",
    short: "Troll",
  },
  {
    name: "centaur",
    id: 96,
    localized_name: "Centaur Warrunner",
    short: "Centaur",
  },
  { name: "magnataur", id: 97, localized_name: "Magnus", short: "Mag" },
  { name: "shredder", id: 98, localized_name: "Timbersaw", short: "Timber" },
  {
    name: "bristleback",
    id: 99,
    localized_name: "Bristleback",
    short: "Bristle",
  },
  { name: "tusk", id: 100, localized_name: "Tusk", short: "Tusk" },
  {
    name: "skywrath_mage",
    id: 101,
    localized_name: "Skywrath Mage",
    short: "Skywrath",
  },
  { name: "abaddon", id: 102, localized_name: "Abaddon", short: "Abba" },
  { name: "elder_titan", id: 103, localized_name: "Elder Titan", short: "ET" },
  {
    name: "legion_commander",
    id: 104,
    localized_name: "Legion Commander",
    short: "LC",
  },
  { name: "techies", id: 105, localized_name: "Techies", short: "Techie" },
  {
    name: "ember_spirit",
    id: 106,
    localized_name: "Ember Spirit",
    short: "Ember",
  },
  {
    name: "earth_spirit",
    id: 107,
    localized_name: "Earth Spirit",
    short: "Earth",
  },
  {
    name: "abyssal_underlord",
    id: 108,
    localized_name: "Underlord",
    short: "Under",
  },
  { name: "terrorblade", id: 109, localized_name: "Terrorblade", short: "TB" },
  { name: "phoenix", id: 110, localized_name: "Phoenix", short: "Phoenix" },
  { name: "oracle", id: 111, localized_name: "Oracle", short: "Oracle" },
  {
    name: "winter_wyvern",
    id: 112,
    localized_name: "Winter Wyvern",
    short: "WW",
  },
  {
    name: "npc_dota_hero_arc_warden",
    id: 113,
    localized_name: "Arc Warden",
    short: "Arc W",
  },
  { name: "monkey_king", id: 114, localized_name: "Monkey King", short: "MK" },
  { name: "dark_willow", id: 119, localized_name: "Dark Willow", short: "DW" },
  { name: "pangolier", id: 120, localized_name: "Pangolier", short: "Pango" },
  { name: "grimstroke", id: 121, localized_name: "Grimstroke", short: "Grim" },
  { name: "hoodwink", id: 123, localized_name: "Hoodwink", short: "Hood" },
  {
    name: "void_spirit",
    id: 126,
    localized_name: "Void Spirit",
    short: "Void Sp",
  },
  { name: "snapfire", id: 128, localized_name: "Snapfire", short: "Snap" },
  { name: "mars", id: 129, localized_name: "Mars", short: "Mars" },
  {
    name: "dawnbreaker",
    id: 135,
    localized_name: "Dawnbreaker",
    short: "Dawn",
  },
  { name: "marci", id: 136, localized_name: "Marci", short: "Marci" },
  {
    name: "primal_beast",
    id: 137,
    localized_name: "Primal Beast",
    short: "Primal B",
  },
  { name: "muerta", id: 138, localized_name: "Muerta", short: "Muerta" },
];

module.exports = { heroes };
